/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;

/**
 *
 * @author AdminSena
 */
public class frmlogin extends javax.swing.JFrame {

    public final JLabel usernameLabel; 
    public final JTextField usernameField; 
    public final JLabel passwordLabel;
    public final JTextField passwordField; 
    public final JButton loginButton; 
    
    /**
     * Creates new form frmlogin
     */
    public frmlogin() {
        initComponents();
        setLayout(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        this.usernameLabel = new JLabel("Username");
        this.passwordLabel = new JLabel("Password");
        this.usernameField = new JTextField();
        this.passwordField = new JTextField();
        this.loginButton = new JButton("Login");
        
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        
        this.usernameLabel.setBounds( 15, 15, screenSize.width, 25 ); 
        this.usernameField.setBounds( 15, 55, screenSize.width, 25 ); 
        this.passwordLabel.setBounds(15, 95, screenSize.width, 25);
        this.passwordField.setBounds(15, 135, screenSize.width, 25);
        this.loginButton.setBounds(15, 175, screenSize.width, 25);
        
        add(this.usernameField); 
        add(this.usernameLabel);
        add(this.passwordField);
        add(this.passwordLabel);
        add(this.loginButton);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
