/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;

/**
 *
 * @author AdminSena
 */
public class frmlogin extends javax.swing.JFrame {

    private final JLabel emailLabel; 
    private final JTextField emailField; 
    private final JLabel passwordLabel;
    private final JTextField passwordField; 
    private final JButton loginButton; 
    private final JButton registerButton;

    /**
     * Creates new form frmlogin
     */
    public frmlogin() {
        initComponents();
        setLayout(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        this.emailLabel = new JLabel("Email");
        this.passwordLabel = new JLabel("Password");
        this.emailField = new JTextField();
        this.passwordField = new JTextField();
        this.loginButton = new JButton("Login");
        this.registerButton = new JButton("Register");

        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        
        this.emailLabel.setBounds( 15, 15, screenSize.width, 25 ); 
        this.emailField.setBounds( 15, 55, screenSize.width, 25 ); 
        this.passwordLabel.setBounds(15, 95, screenSize.width, 25);
        this.passwordField.setBounds(15, 135, screenSize.width, 25);
        this.loginButton.setBounds(15, 175, screenSize.width, 25);
        this.registerButton.setBounds(15, 215, screenSize.width, 25);

        add(this.emailField); 
        add(this.emailLabel);
        add(this.passwordField);
        add(this.passwordLabel);
        add(this.loginButton);                                      
        add(this.registerButton);
        
    }

    public JButton getLoginButton() {
        return loginButton;
    }

    public JButton getRegisterButton() {
        return registerButton;
    }

    public JTextField getPasswordField() {
        return passwordField;
    }

    public JTextField getEmailField() {
        return emailField;
    }

    public JLabel getEmailLabel() {
        return emailLabel;
    }

    public JLabel getPasswordLabel() {
        return passwordLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
