/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author AdminSena
 */
public class frmregistro extends javax.swing.JFrame {
    
    private final JButton sendButton; 
    private final JLabel nameLabel;
    private final JLabel lastNameLabel;
    private final JLabel emailLabel;
    private final JLabel passwordLabel;
    private final JLabel userTypeComboBoxLabel;
    private final JTextField nameField; 
    private final JTextField lastNameField; 
    private final JTextField emailField; 
    private final JTextField passwordField; 
    private final JComboBox userTypeComboBox;
            
    /**
     * Creates new form frmregistro
     */
    public frmregistro() {
        setLayout(null); 
        initComponents();
        setTitle("Registry"); 
        
        this.sendButton = new JButton("Register");
        this.nameLabel = new JLabel("Name");
        this.lastNameLabel = new JLabel("Last Name");
        this.emailLabel = new JLabel("Email");
        this.passwordLabel = new JLabel("Password");
        this.userTypeComboBoxLabel = new JLabel("User type");
        
        this.nameField = new JTextField();
        this.lastNameField = new JTextField();
        this.emailField = new JTextField();
        this.passwordField = new JTextField();
        
        this.userTypeComboBox = new JComboBox();
        
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        
        this.nameLabel.setBounds(15, 15, screenSize.width - 40, 25);
        this.nameField.setBounds(15, 55, screenSize.width - 40, 25);
        this.lastNameLabel.setBounds(15, 95, screenSize.width - 40, 25);
        this.lastNameField.setBounds(15, 135, screenSize.width - 40, 25);
        this.emailLabel.setBounds(15, 175, screenSize.width - 40, 25);
        this.emailField.setBounds(15, 215, screenSize.width - 40, 25);
        this.passwordLabel.setBounds(15, 255, screenSize.width - 40, 25);
        this.passwordField.setBounds(15, 295, screenSize.width - 40, 25);
        this.sendButton.setBounds(15, 335, screenSize.width - 40, 25);
        
        add( this.nameLabel );
        add( this.nameField ); 
        add( this.lastNameLabel );
        add( this.lastNameField );
        add( this.emailLabel );
        add( this.emailField );
        add( this.passwordLabel );
        add( this.passwordField );
        add( this.userTypeComboBoxLabel );
        add( this.userTypeComboBox );
        add( this.sendButton );
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
